-- ============================================================================
-- BETTER AUTH TABLES
-- ============================================================================
-- Tables for Better Auth authentication system integration.
-- Better Auth runs as a separate Node.js microservice and shares this database
-- with the FastAPI backend for session validation.
--
-- Key Features:
-- - Cookie-based sessions with httpOnly for security
-- - Email/password authentication support
-- - OAuth account linking support
-- - Email verification system
--
-- Dependencies: None (standalone auth system)

-- ═══════════════════════════════════════════════════════════
-- USERS TABLE
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS "user" (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    email_verified BOOLEAN DEFAULT FALSE,
    image TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_email ON "user"(email);

COMMENT ON TABLE "user" IS 'Better Auth users table for authentication';
COMMENT ON COLUMN "user".id IS 'User unique identifier (generated by Better Auth)';
COMMENT ON COLUMN "user".name IS 'User display name';
COMMENT ON COLUMN "user".email IS 'User email address (unique)';
COMMENT ON COLUMN "user".email_verified IS 'Whether email has been verified';
COMMENT ON COLUMN "user".image IS 'User profile image URL (optional)';


-- ═══════════════════════════════════════════════════════════
-- SESSIONS TABLE
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS session (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_session_token ON session(token);
CREATE INDEX IF NOT EXISTS idx_session_user_id ON session(user_id);
CREATE INDEX IF NOT EXISTS idx_session_expires_at ON session(expires_at);

COMMENT ON TABLE session IS 'Better Auth sessions for logged-in users';
COMMENT ON COLUMN session.id IS 'Session unique identifier';
COMMENT ON COLUMN session.user_id IS 'User ID this session belongs to';
COMMENT ON COLUMN session.token IS 'Session token stored in httpOnly cookie';
COMMENT ON COLUMN session.expires_at IS 'Session expiration timestamp';
COMMENT ON COLUMN session.ip_address IS 'IP address of session creator';
COMMENT ON COLUMN session.user_agent IS 'User agent string of session creator';


-- ═══════════════════════════════════════════════════════════
-- ACCOUNTS TABLE
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS account (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    account_id TEXT NOT NULL,
    provider_id TEXT NOT NULL,
    access_token TEXT,
    refresh_token TEXT,
    access_token_expires_at TIMESTAMPTZ,
    refresh_token_expires_at TIMESTAMPTZ,
    scope TEXT,
    id_token TEXT,
    password TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_account_user_id ON account(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_account_provider ON account(provider_id, account_id);

COMMENT ON TABLE account IS 'Better Auth accounts (OAuth and password auth)';
COMMENT ON COLUMN account.id IS 'Account unique identifier';
COMMENT ON COLUMN account.user_id IS 'User ID this account belongs to';
COMMENT ON COLUMN account.account_id IS 'External account ID (from OAuth provider)';
COMMENT ON COLUMN account.provider_id IS 'Auth provider ID (e.g., google, github, password)';
COMMENT ON COLUMN account.access_token IS 'OAuth access token (for OAuth providers)';
COMMENT ON COLUMN account.refresh_token IS 'OAuth refresh token (for OAuth providers)';
COMMENT ON COLUMN account.access_token_expires_at IS 'Access token expiration';
COMMENT ON COLUMN account.refresh_token_expires_at IS 'Refresh token expiration';
COMMENT ON COLUMN account.scope IS 'OAuth scope granted';
COMMENT ON COLUMN account.id_token IS 'OAuth ID token';
COMMENT ON COLUMN account.password IS 'Hashed password (for email/password auth)';


-- ═══════════════════════════════════════════════════════════
-- VERIFICATION TABLE
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS verification (
    id TEXT PRIMARY KEY,
    identifier TEXT NOT NULL,
    value TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_verification_identifier ON verification(identifier);

COMMENT ON TABLE verification IS 'Better Auth verification tokens (email verification, password reset)';
COMMENT ON COLUMN verification.id IS 'Verification token unique identifier';
COMMENT ON COLUMN verification.identifier IS 'What is being verified (email address, etc.)';
COMMENT ON COLUMN verification.value IS 'Verification code/token';
COMMENT ON COLUMN verification.expires_at IS 'Verification expiration timestamp';
